version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - /home/pi/docker/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  telegraf:
    image: telegraf:latest
    user: "1000"
    volumes:
      - /home/pi/docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    ports:
      - 3000:3000
    volumes:
      - /home/pi/docker/grafana:/var/lib/grafana
      - /home/pi/docker/grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin